root: true

env:
  node: true
  browser: true
  es6: true

rules:
  indent: [2, 2]
  quotes: [2, "single"]
  linebreak-style: [2, "unix"]
  semi: [2, always]
  no-console: 0

extends: "eslint:recommended"
